### PR TITLE
add donut

### PR DESCRIPTION
**Pull request by Ellrion**
use `donutWidth` and `donutColor` for configure pie chart like donut chart

### CODE REVIEW

**Comment by imsky** [comment]
:+1:

**Comment by Ellrion** [comment]
please create new releas v2.4.1

**Comment by imsky** [comment]
will do

**Comment by imsky** [comment]
now available @Ellrion https://github.com/imsky/jquery.sparkline/releases/tag/v2.4.0

**Comment by Ellrion** [comment]
@imsky , add release to npm as well please

**Comment by imsky** [comment]
@Ellrion done

**Pull request merged**
